
builds:
  - 
    main: ./cmd/helmper
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      # - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X github.com/ChristofferNissen/helmper/internal.version={{ .Version }} -X github.com/ChristofferNissen/helmper/internal.commit={{ .Commit }} -X github.com/ChristofferNissen/helmper/internal.date={{ .CommitDate }}"

archives:
  - id: archives
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"

snapshot:
  name_template: "git-{{.Commit}}"

release:
  name_template: "v{{.Version}}"

changelog:
  skip: true

dockers:
  - image_templates: ["ghcr.io/sboschman/{{ .ProjectName }}:{{ .Version }}-amd64"]
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
